name: Deploy

on: 
  push:
    branches:
      - master

jobs: 
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v2
      - users: actions/setup-node@v2
        with:
          node-version: '14'
      - name: npm install
        env:
          CI: true
        run: |
          npm ci