name: Deploy

on: 
  push:
    branches:
      - master

jobs: 
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        users: actions/checkout@v1
        with:
          node-version: '14'
      - name: npm install
        env:
          CI: true
        run: |
          npm ci